<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Tutor;
use Illuminate\Support\Facades\Hash;

class AdditionalTutorsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tutors = [
            [
                'tutorID' => 'OGS-T0025',
                'first_name' => 'Michael',
                'last_name' => 'Anderson',
                'tusername' => 'michaelanderson',
                'tpassword' => Hash::make('password123'),
                'email' => 'michael.anderson@ogsconnect.com',
                'phone_number' => '+1-555-0101',
                'sex' => 'M',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0026',
                'first_name' => 'Sarah',
                'last_name' => 'Thompson',
                'tusername' => 'sarahthompson',
                'tpassword' => Hash::make('password123'),
                'email' => 'sarah.thompson@ogsconnect.com',
                'phone_number' => '+1-555-0102',
                'sex' => 'F',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0027',
                'first_name' => 'David',
                'last_name' => 'Martinez',
                'tusername' => 'davidmartinez',
                'tpassword' => Hash::make('password123'),
                'email' => 'david.martinez@ogsconnect.com',
                'phone_number' => '+1-555-0103',
                'sex' => 'M',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0028',
                'first_name' => 'Jennifer',
                'last_name' => 'Garcia',
                'tusername' => 'jennifergarcia',
                'tpassword' => Hash::make('password123'),
                'email' => 'jennifer.garcia@ogsconnect.com',
                'phone_number' => '+1-555-0104',
                'sex' => 'F',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0029',
                'first_name' => 'Christopher',
                'last_name' => 'Wilson',
                'tusername' => 'christopherwilson',
                'tpassword' => Hash::make('password123'),
                'email' => 'christopher.wilson@ogsconnect.com',
                'phone_number' => '+1-555-0105',
                'sex' => 'M',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0030',
                'first_name' => 'Amanda',
                'last_name' => 'Brown',
                'tusername' => 'amandabrown',
                'tpassword' => Hash::make('password123'),
                'email' => 'amanda.brown@ogsconnect.com',
                'phone_number' => '+1-555-0106',
                'sex' => 'F',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0031',
                'first_name' => 'Matthew',
                'last_name' => 'Davis',
                'tusername' => 'matthewdavis',
                'tpassword' => Hash::make('password123'),
                'email' => 'matthew.davis@ogsconnect.com',
                'phone_number' => '+1-555-0107',
                'sex' => 'M',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0032',
                'first_name' => 'Jessica',
                'last_name' => 'Miller',
                'tusername' => 'jessicamiller',
                'tpassword' => Hash::make('password123'),
                'email' => 'jessica.miller@ogsconnect.com',
                'phone_number' => '+1-555-0108',
                'sex' => 'F',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0033',
                'first_name' => 'Daniel',
                'last_name' => 'Moore',
                'tusername' => 'danielmoore',
                'tpassword' => Hash::make('password123'),
                'email' => 'daniel.moore@ogsconnect.com',
                'phone_number' => '+1-555-0109',
                'sex' => 'M',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0034',
                'first_name' => 'Ashley',
                'last_name' => 'Taylor',
                'tusername' => 'ashleytaylor',
                'tpassword' => Hash::make('password123'),
                'email' => 'ashley.taylor@ogsconnect.com',
                'phone_number' => '+1-555-0110',
                'sex' => 'F',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0035',
                'first_name' => 'Andrew',
                'last_name' => 'Jackson',
                'tusername' => 'andrewjackson',
                'tpassword' => Hash::make('password123'),
                'email' => 'andrew.jackson@ogsconnect.com',
                'phone_number' => '+1-555-0111',
                'sex' => 'M',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0036',
                'first_name' => 'Stephanie',
                'last_name' => 'White',
                'tusername' => 'stephaniewhite',
                'tpassword' => Hash::make('password123'),
                'email' => 'stephanie.white@ogsconnect.com',
                'phone_number' => '+1-555-0112',
                'sex' => 'F',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0037',
                'first_name' => 'Joshua',
                'last_name' => 'Harris',
                'tusername' => 'joshuaharris',
                'tpassword' => Hash::make('password123'),
                'email' => 'joshua.harris@ogsconnect.com',
                'phone_number' => '+1-555-0113',
                'sex' => 'M',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0038',
                'first_name' => 'Nicole',
                'last_name' => 'Martin',
                'tusername' => 'nicolemartin',
                'tpassword' => Hash::make('password123'),
                'email' => 'nicole.martin@ogsconnect.com',
                'phone_number' => '+1-555-0114',
                'sex' => 'F',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0039',
                'first_name' => 'Kevin',
                'last_name' => 'Thompson',
                'tusername' => 'kevinthompson',
                'tpassword' => Hash::make('password123'),
                'email' => 'kevin.thompson@ogsconnect.com',
                'phone_number' => '+1-555-0115',
                'sex' => 'M',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0040',
                'first_name' => 'Elizabeth',
                'last_name' => 'Garcia',
                'tusername' => 'elizabethgarcia',
                'tpassword' => Hash::make('password123'),
                'email' => 'elizabeth.garcia@ogsconnect.com',
                'phone_number' => '+1-555-0116',
                'sex' => 'F',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0041',
                'first_name' => 'Brian',
                'last_name' => 'Martinez',
                'tusername' => 'brianmartinez',
                'tpassword' => Hash::make('password123'),
                'email' => 'brian.martinez@ogsconnect.com',
                'phone_number' => '+1-555-0117',
                'sex' => 'M',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0042',
                'first_name' => 'Megan',
                'last_name' => 'Robinson',
                'tusername' => 'meganrobinson',
                'tpassword' => Hash::make('password123'),
                'email' => 'megan.robinson@ogsconnect.com',
                'phone_number' => '+1-555-0118',
                'sex' => 'F',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0043',
                'first_name' => 'Timothy',
                'last_name' => 'Clark',
                'tusername' => 'timothyclark',
                'tpassword' => Hash::make('password123'),
                'email' => 'timothy.clark@ogsconnect.com',
                'phone_number' => '+1-555-0119',
                'sex' => 'M',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0044',
                'first_name' => 'Rachel',
                'last_name' => 'Rodriguez',
                'tusername' => 'rachelrodriguez',
                'tpassword' => Hash::make('password123'),
                'email' => 'rachel.rodriguez@ogsconnect.com',
                'phone_number' => '+1-555-0120',
                'sex' => 'F',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0045',
                'first_name' => 'Jonathan',
                'last_name' => 'Lewis',
                'tusername' => 'jonathanlewis',
                'tpassword' => Hash::make('password123'),
                'email' => 'jonathan.lewis@ogsconnect.com',
                'phone_number' => '+1-555-0121',
                'sex' => 'M',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0046',
                'first_name' => 'Lauren',
                'last_name' => 'Lee',
                'tusername' => 'laurenlee',
                'tpassword' => Hash::make('password123'),
                'email' => 'lauren.lee@ogsconnect.com',
                'phone_number' => '+1-555-0122',
                'sex' => 'F',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0047',
                'first_name' => 'Nathan',
                'last_name' => 'Walker',
                'tusername' => 'nathanwalker',
                'tpassword' => Hash::make('password123'),
                'email' => 'nathan.walker@ogsconnect.com',
                'phone_number' => '+1-555-0123',
                'sex' => 'M',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0048',
                'first_name' => 'Samantha',
                'last_name' => 'Hall',
                'tusername' => 'samanthahall',
                'tpassword' => Hash::make('password123'),
                'email' => 'samantha.hall@ogsconnect.com',
                'phone_number' => '+1-555-0124',
                'sex' => 'F',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0049',
                'first_name' => 'Brandon',
                'last_name' => 'Allen',
                'tusername' => 'brandonallen',
                'tpassword' => Hash::make('password123'),
                'email' => 'brandon.allen@ogsconnect.com',
                'phone_number' => '+1-555-0125',
                'sex' => 'M',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tutorID' => 'OGS-T0050',
                'first_name' => 'Victoria',
                'last_name' => 'Young',
                'tusername' => 'victoriayoung',
                'tpassword' => Hash::make('password123'),
                'email' => 'victoria.young@ogsconnect.com',
                'phone_number' => '+1-555-0126',
                'sex' => 'F',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($tutors as $tutorData) {
            Tutor::create($tutorData);
        }

        $this->command->info('Successfully added 26 additional tutors to the system.');
    }
}