<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payslip</title>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            background: #f5f6fa;
            margin: 0;
            padding: 20px;
        }
        .container {
            background: #ffffff;
            max-width: 650px;
            margin: auto;
            border-radius: 10px;
            padding: 25px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.08);
        }
        h2 {
            color: #0E335D;
            margin-bottom: 10px;
        }
        p { color: #333; }
        .summary-box {
            background: #f0f4ff;
            border-left: 4px solid #0E335D;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 6px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            font-size: 14px;
        }
        th {
            background: #0E335D;
            color: white;
            padding: 10px;
            text-align: left;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }
        .totals {
            font-weight: bold;
        }
        .footer {
            margin-top: 25px;
            font-size: 13px;
            text-align: center;
            color: #777;
        }
    </style>
</head>

<body>
    <div class="container">

        <h2>Payslip for {{ $tutor->full_name }}</h2>
        <p>Below are the details for this pay period.</p>

        <div class="summary-box">
            @php
                $tenureYears = null;
                $tenureAmount = 0;
                if (!empty($tutor->hired_date_time)) {
                    $hired = \Carbon\Carbon::parse($tutor->hired_date_time);
                    $tenureYears = round($hired->diffInYears(\Carbon\Carbon::now()));
                    $tenureAmount = $tenureYears * 10; // ₱10 per year
                }
                $gross = $totalEarnings ?? 0;
                $deduct = $deductions ?? 0;
                $net = $gross + $tenureAmount - $deduct;
            @endphp

            <p><strong>Pay Period:</strong> {{ $periodStart }} to {{ $periodEnd }}</p>
            <p><strong>Gross Pay:</strong> ₱{{ number_format($gross,2) }}</p>
            <p><strong>Deductions:</strong> ₱{{ number_format($deduct,2) }}</p>
            <p><strong>Tenure Bonus:</strong>
                @if(!is_null($tenureYears))
                    ₱{{ number_format($tenureAmount,2) }} ({{ $tenureYears }} year(s))
                @else
                    —
                @endif
            </p>
            <p><strong>Net Pay:</strong> ₱{{ number_format($net,2) }}</p>
        </div>

        <h3>Approved Work</h3>

        <table>
            <tr>
                <th>Date</th>
                <th>Type</th>
                <th>Duration</th>
                <th>Amount (₱)</th>
            </tr>

            @foreach ($details as $d)
                @php
                    if ($d->start_time && $d->end_time) {
                        $start = \Carbon\Carbon::parse($d->start_time);
                        $end   = \Carbon\Carbon::parse($d->end_time);
                        if ($end->lessThan($start)) $end->addDay();
                        $minutes = $start->diffInMinutes($end);
                        $hours = floor($minutes / 60);
                        $mins  = $minutes % 60;
                        $duration = sprintf('%02d:%02d',$hours,$mins);
                    } else {
                        $duration = '—';
                    }
                    $amount = $d->work_type === 'hourly'
                        ? round(($minutes / 60) * ($d->rate_per_hour ?? 0), 2)
                        : $d->rate_per_class ?? 0;
                @endphp

                <tr>
                    <td>{{ $d->day ?? $d->created_at?->format('Y-m-d') }}</td>
                    <td>{{ ucfirst($d->work_type) }}</td>
                    <td>{{ $duration }}</td>
                    <td>{{ number_format($amount, 2) }}</td>
                </tr>
            @endforeach
        </table>

        <p class="footer">This is an automated message generated by OGS Connect.</p>
    </div>
</body>
</html>
